
In all the Notebooks we follow the same conventions to make the code more readable.

* Function arguments start with and underline (e.g. `_x`), while function internal variables do not (e.g. `x`).
* Often we simply write 'array', by this we mean Numpy arrays specifically.
* It is important to know when we use lists and when we use arrays. The distinction will be made clear in the code's comments.
* In the code, we refer to the miners as miner `0` and miner `1` instead of as miner `1` and `2`. This is because we start to count at `0` in Python.
* We make use of recursion. This is slow, but it is elegant and improves readability as well as comprehensibility.

This notebook serves as a hub for all the simulation output. The reader may refer to the other notebooks for the inner-workings of the simulations.

## Main

Notes specific to this notebook: 
* When the output says that it checked all situations for height $h$, it means that for all possible situations at the beginning of stage $t=h+1$, the conjecture was not violated in any of the subsequent intermediate stages $t,\dots,T$. A block’s height is equal to its index, which is equal to the stage it was mined in.
* We start checking the conjectures in stage $t=2$. The first stage ($t=1$) can be skipped because we assume w.l.o.g. that miner `0` wins that stage. This also means that we can skip the two-stage game, because we know what the Nash equilibrium in the second stage of the two-stage game looks like, and that it does not violate any conjectures.

In [2]:
#IMPORTS
#libraries
import numpy as np
import time
import platform
import psutil
import cpuinfo #the package is called 'py-cpuinfo'
import import_ipynb

#notebooks
import blockchain as bc
import helper_functions as helfun
import payoff_matrix as pm
import conjectures

#SYSTEM SPECIFICATIONS
print("\n### System Specifications ###")
print("System:", platform.system())
print("Architecture:", cpuinfo.get_cpu_info()["arch"])
print("CPU:", cpuinfo.get_cpu_info()["brand_raw"])
print("CPU Cores:", psutil.cpu_count(logical=True)) 
print("Memory:", round(psutil.virtual_memory().total / (1024 ** 3), 2), "Gigabytes")

#VERSIONS
print("\n### Versions ###")
print("Python", platform.python_version()) #3.10.6
print("Numpy", np.__version__) #1.25.0


importing Jupyter notebook from blockchain.ipynb
importing Jupyter notebook from helper_functions.ipynb
importing Jupyter notebook from payoff_matrix.ipynb
importing Jupyter notebook from conjectures.ipynb

### System Specifications ###
System: Windows
Architecture: X86_64
CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
CPU Cores: 8
Memory: 31.92 Gigabytes

### Versions ###
Python 3.10.6
Numpy 1.25.0


### Conjecture 1
_Forks_. It is important to note that it is sufficient to check if there are forks to test conjecture 1, because we know that this is equivalent thanks to lemma 1. The relevant function, `Forks()`, is defined in `conjectures.ipynb`.

In [2]:
n = 2
max_horizon = 7

#test all equilibrium paths for forks
for T in range(3, max_horizon+1):
    start = time.process_time()
    print(f'found a fork for T={T}? ', conjectures.Forks(T, n))
    end = time.process_time()
    print(helfun.timeElapsed(start, end))
    print("")

print("done")

found a fork for T=3?  False
0.0 seconds

found a fork for T=4?  False
0.2 seconds

found a fork for T=5?  False
11.0 seconds

found a fork for T=6?  False
13 minutes

found a fork for T=7?  False
24 hours

done


### Conjecture 2

_Monotonicity_. The relevant function, `Monotonicity()`, is defined in `conjectures.ipynb`.

In [3]:
for T in range(3, max_horizon+1):
    start = time.process_time()
    conjectures.Monotonicity(T, n)
    end = time.process_time()
    print(helfun.timeElapsed(start, end))
    print("")

print("done")

checked height 1 in games with T = 3 stages
0.0 seconds

checked height 1 in games with T = 4 stages
checked height 2 in games with T = 4 stages
0.3 seconds

checked height 1 in games with T = 5 stages
checked height 2 in games with T = 5 stages
checked height 3 in games with T = 5 stages
17.8 seconds

checked height 1 in games with T = 6 stages
checked height 2 in games with T = 6 stages
checked height 3 in games with T = 6 stages
checked height 4 in games with T = 6 stages
22 minutes

checked height 1 in games with T = 7 stages
checked height 2 in games with T = 7 stages
checked height 3 in games with T = 7 stages
checked height 4 in games with T = 7 stages
checked height 5 in games with T = 7 stages
39 hours

done


### Conjecture 3

_A miner's behaviour after winning their first block_. The relevant function, `FirstBlock()`, is defined in `conjectures.ipynb`.

In [4]:
for T in range(3, max_horizon+1):
    start = time.process_time()
    conjectures.FirstBlock(T, n)
    end = time.process_time()
    print(helfun.timeElapsed(start, end))
    print("")

print("done")

checked height 1 in games with T = 3 stages
0.0 seconds

checked height 1 in games with T = 4 stages
checked height 2 in games with T = 4 stages
0.2 seconds

checked height 1 in games with T = 5 stages
checked height 2 in games with T = 5 stages
checked height 3 in games with T = 5 stages
12.8 seconds

checked height 1 in games with T = 6 stages
checked height 2 in games with T = 6 stages
checked height 3 in games with T = 6 stages
checked height 4 in games with T = 6 stages
16 minutes

checked height 1 in games with T = 7 stages
checked height 2 in games with T = 7 stages
checked height 3 in games with T = 7 stages
checked height 4 in games with T = 7 stages
checked height 5 in games with T = 7 stages
29 hours

done


### Conjecture 4

_Switching to shorter chains_. The relevant function, `Switching()`, is defined in `conjectures.ipynb`.

In [5]:
for T in range(3, max_horizon+1):
    start = time.process_time()
    conjectures.Switching(T, n)
    end = time.process_time()
    print(helfun.timeElapsed(start, end))
    print("")

print("done")

checked height 1 in games with T = 3 stages
0.0 seconds

checked height 1 in games with T = 4 stages
checked height 2 in games with T = 4 stages
0.3 seconds

checked height 1 in games with T = 5 stages
checked height 2 in games with T = 5 stages
checked height 3 in games with T = 5 stages
18.3 seconds

checked height 1 in games with T = 6 stages
checked height 2 in games with T = 6 stages
checked height 3 in games with T = 6 stages
checked height 4 in games with T = 6 stages
23 minutes

checked height 1 in games with T = 7 stages
checked height 2 in games with T = 7 stages
checked height 3 in games with T = 7 stages
checked height 4 in games with T = 7 stages
checked height 5 in games with T = 7 stages
41 hours

done


### Conjecture 5

_Coordination_. The relevant function, `Coordination()`, is defined in `conjectures.ipynb`.

In [6]:
for T in range(3, max_horizon+1):
    start = time.process_time()
    conjectures.Coordination(T, n)
    end = time.process_time()
    print(helfun.timeElapsed(start, end))
    print("")

print("done")

checked stage t = 2 in games with T = 3 stages
checked stage t = 3 in games with T = 3 stages
0.0 seconds

checked stage t = 2 in games with T = 4 stages
checked stage t = 3 in games with T = 4 stages
checked stage t = 4 in games with T = 4 stages
0.3 seconds

checked stage t = 2 in games with T = 5 stages
checked stage t = 3 in games with T = 5 stages
checked stage t = 4 in games with T = 5 stages
checked stage t = 5 in games with T = 5 stages
15.2 seconds

checked stage t = 2 in games with T = 6 stages
checked stage t = 3 in games with T = 6 stages
checked stage t = 4 in games with T = 6 stages
checked stage t = 5 in games with T = 6 stages
checked stage t = 6 in games with T = 6 stages
19 minutes

checked stage t = 2 in games with T = 7 stages
checked stage t = 3 in games with T = 7 stages
checked stage t = 4 in games with T = 7 stages
checked stage t = 5 in games with T = 7 stages
checked stage t = 6 in games with T = 7 stages
checked stage t = 7 in games with T = 7 stages
33 hours

## Payoff Matrices
The code below generates all the payoff-matrices shown in the thesis. 

In [7]:
#PRINT PAYOFF MATRICES IN SECOND STAGE FOR GAMES OF HORIZON 'T'
for T in range(2, max_horizon+1):

    #BLOCKCHAIN WITH TWO BLOCKS, b0 and b1
    parents = np.array([0])
    winners = np.array([0]) #w.l.o.g. miner 0 wins the first stage

    B = bc.Blockchain(n, parents, winners)

    start = time.process_time()
    print(f"\npayoff-matrix for t = 2 and T = {T}:\n\n", pm.intermediatePayoffMatrix(B, T, n))
    end = time.process_time()
    print("\n", helfun.timeElapsed(start, end), "\n")




payoff-matrix for t = 2 and T = 2:

 [[[0.75 0.25]
  [1.   0.5 ]]

 [[1.25 0.25]
  [1.5  0.5 ]]]

 0.0 seconds 


payoff-matrix for t = 2 and T = 3:

 [[[1.25 0.75]
  [1.5  1.  ]]

 [[1.75 0.75]
  [2.   1.  ]]]

 0.0 seconds 


payoff-matrix for t = 2 and T = 4:

 [[[1.6875 1.1875]
  [2.     1.5   ]]

 [[2.1875 1.1875]
  [2.5    1.5   ]]]

 0.2 seconds 


payoff-matrix for t = 2 and T = 5:

 [[[2.1875 1.6875]
  [2.5    2.    ]]

 [[2.6875 1.6875]
  [3.     2.    ]]]

 8.6 seconds 


payoff-matrix for t = 2 and T = 6:

 [[[2.75 2.25]
  [3.   2.5 ]]

 [[3.25 2.25]
  [3.5  2.5 ]]]

 10 minutes 


payoff-matrix for t = 2 and T = 7:

 [[[3.25 2.75]
  [3.5  3.  ]]

 [[3.75 2.75]
  [4.   3.  ]]]

 18 hours 



Next we generate payoff-matrices for specific blockchains (a), (b), (c) and (d) in the three-stage game.

In [4]:
#BLOCKCHAIN (a) IN THREE-STAGE GAME
parents = np.array([0, 1]) #block b1 is appended to the genesis block, block b2 is appended to b1
winners = np.array([0, 0]) #miner 0 wins the first and second stage
helfun.printPayoffMatrix(n, parents, winners, "(a)", 3)


#BLOCKCHAIN (b) IN THREE-STAGE GAME
parents = np.array([0, 1]) #block b1 is appended to the genesis block, block b2 is appended to b1
winners = np.array([0, 1]) #miner 0 wins the first stage, miner 1 wins the second stage
helfun.printPayoffMatrix(n, parents, winners, "(b)", 3)


#BLOCKCHAIN (c) IN THREE-STAGE GAME
parents = np.array([0, 0]) #both blocks b1 and b2 are appended to the genesis block
winners = np.array([0, 0]) #miner 0 wins the first and second stage
helfun.printPayoffMatrix(n, parents, winners, "(c)", 3)


#BLOCKCHAIN (d) IN THREE-STAGE GAME
parents = np.array([0, 0]) #both blocks b1 and b2 are appended to the genesis block
winners = np.array([0, 1]) #miner 0 wins the first stage, miner 1 wins the second stage
helfun.printPayoffMatrix(n, parents, winners, "(d)", 3)



blockchain (a):

b0
└── b1
    └── b2

miner 0 wins stages [1 2]
miner 1 wins stages []

payoff-matrix for blockchain (a) in 3-stage game:

 [[[2.   0.  ]
  [1.75 0.25]
  [2.   0.5 ]]

 [[2.   0.  ]
  [1.75 0.25]
  [2.   0.5 ]]

 [[2.5  0.  ]
  [2.25 0.25]
  [2.5  0.5 ]]]

 0.0 seconds 

blockchain (b):

b0
└── b1
    └── b2

miner 0 wins stages [1]
miner 1 wins stages [2]

payoff-matrix for blockchain (b) in 3-stage game:

 [[[1.   1.  ]
  [1.   1.  ]
  [1.   1.5 ]]

 [[1.25 0.75]
  [1.25 0.75]
  [1.25 1.25]]

 [[1.5  1.  ]
  [1.5  1.  ]
  [1.5  1.5 ]]]

 0.0 seconds 

blockchain (c):

b0
├── b1
└── b2

miner 0 wins stages [1 2]
miner 1 wins stages []

payoff-matrix for blockchain (c) in 3-stage game:

 [[[0.83333333 0.16666667]
  [1.         0.5       ]
  [1.         0.5       ]]

 [[1.33333333 0.16666667]
  [1.5        0.5       ]
  [1.5        0.5       ]]

 [[1.33333333 0.16666667]
  [1.5        0.5       ]
  [1.5        0.5       ]]]

 0.0 seconds 

blockchain (d):

b0
├── b1
└──

Next we generate payoff-matrices for specific blockchains (a), (b), (e), (f), (g) and (h) in the four-stage game.

In [5]:
#BLOCKCHAIN (a) IN FOUR-STAGE GAME
parents = np.array([0, 1]) #block b1 is appended to the genesis block, block b2 is appended to b1
winners = np.array([0, 0]) #miner 0 wins the first and second stage
helfun.printPayoffMatrix(n, parents, winners, "(a)", 4)


#BLOCKCHAIN (b) IN FOUR-STAGE GAME
parents = np.array([0, 1]) #block b1 is appended to the genesis block, block b2 is appended to b1
winners = np.array([0, 1]) #miner 0 wins the first stage, miner 1 wins the second stage
helfun.printPayoffMatrix(n, parents, winners, "(b)", 4)

#BLOCKCHAIN (e) IN FOUR-STAGE GAME
parents = np.array([0, 1, 2]) #block b1 is appended to the genesis block, block b2 is appended to b1, block b3 is appended to b2
winners = np.array([0, 1, 0]) #miner 0 wins the first and third stages, miner 2 wins the second stage
helfun.printPayoffMatrix(n, parents, winners, "(e)", 4)


#BLOCKCHAIN (f) IN FOUR-STAGE GAME
parents = np.array([0, 1, 2]) #block b1 is appended to the genesis block, block b2 is appended to b1, block b3 is appended to b2
winners = np.array([0, 1, 1]) #miner 0 wins the first stage, miner 2 wins the second and third stages
helfun.printPayoffMatrix(n, parents, winners, "(f)", 4)

#BLOCKCHAIN (g) IN FOUR-STAGE GAME
parents = np.array([0, 1, 2]) #block b1 is appended to the genesis block, block b2 is appended to b1, block b3 is appended to b2
winners = np.array([0, 0, 0]) #miner 0 wins the first, second and third stages
helfun.printPayoffMatrix(n, parents, winners, "(g)", 4)


#BLOCKCHAIN (h) IN FOUR-STAGE GAME
parents = np.array([0, 1, 2]) #block b1 is appended to the genesis block, block b2 is appended to b1, block b3 is appended to b2
winners = np.array([0, 0, 1]) #miner 0 wins the first and second stages, miner 1 wins the third stage
helfun.printPayoffMatrix(n, parents, winners, "(h)", 4)



blockchain (a):

b0
└── b1
    └── b2

miner 0 wins stages [1 2]
miner 1 wins stages []

payoff-matrix for blockchain (a) in 4-stage game:

 [[[2.375 0.5  ]
  [2.25  0.75 ]
  [2.5   1.   ]]

 [[2.375 0.5  ]
  [2.25  0.75 ]
  [2.5   1.   ]]

 [[2.875 0.5  ]
  [2.75  0.75 ]
  [3.    1.   ]]]

 0.0 seconds 

blockchain (b):

b0
└── b1
    └── b2

miner 0 wins stages [1]
miner 1 wins stages [2]

payoff-matrix for blockchain (b) in 4-stage game:

 [[[1.5  1.5 ]
  [1.5  1.5 ]
  [1.5  2.  ]]

 [[1.75 1.25]
  [1.75 1.25]
  [1.75 1.75]]

 [[2.   1.5 ]
  [2.   1.5 ]
  [2.   2.  ]]]

 0.0 seconds 

blockchain (e):

b0
└── b1
    └── b2
        └── b3

miner 0 wins stages [1 3]
miner 1 wins stages [2]

payoff-matrix for blockchain (e) in 4-stage game:

 [[[2.   1.  ]
  [2.   1.  ]
  [1.75 1.25]
  [2.   1.5 ]]

 [[2.   1.  ]
  [2.   1.  ]
  [1.75 1.25]
  [2.   1.5 ]]

 [[2.   1.  ]
  [2.   1.  ]
  [1.75 1.25]
  [2.   1.5 ]]

 [[2.5  1.  ]
  [2.5  1.  ]
  [2.25 1.25]
  [2.5  1.5 ]]]

 0.0 seconds 

